spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_cars
    username: postgres
    password: "0720"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml